stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: openjdk:8u222
  variables:
    POSTGRES_PASSWORD: "postgres_234"
  services:
    - name: postgres:9.6
      alias: db
  script:
    - ./mvnw test -Dquarkus.profile=test
  except:
    - tags
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

build:
  stage: build
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:18.09-dind
      command: ["--insecure-registry=registry.balcia.com"]
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  except:
    - tags

build:ver:
  stage: build
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:18.09-dind
      command: ["--insecure-registry=registry.balcia.com"]
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
    - tags

deploy:
  stage: deploy
  image: gintsgints/helm-kubectl-docker
  variables:
    KUBECONFIG: /etc/deploy/config
    KUBE_NAMESPACE: develop
  before_script:
    - mkdir -p /etc/deploy
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
  script:
    - kubectl apply --namespace "$KUBE_NAMESPACE" -f ./k8s/db-deployment.yaml
    - kubectl apply --namespace "$KUBE_NAMESPACE" -f ./k8s/db-service.yaml
    - kubectl apply --namespace "$KUBE_NAMESPACE" -f ./k8s/server-deployment.yaml
    - kubectl apply --namespace "$KUBE_NAMESPACE" -f ./k8s/server-service.yaml
  environment:
    name: develop
    url: http://10.203.8.21:30310
  except:
    - tags
