version: '3'

services:
  server:
    image: registry.balcia.com/balcia_dev/java/quarkus-ws
    ports:
      - '8080:8080'
      - '8778:8778'
      - '9779:9779'
    environment:
      - POSTGRES_PASSWORD=postgres_234
      - MYSQL_HOST=db
      - QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak:8080/auth/realms/quarkus
      - QUARKUS_PROFILE=dev

  keycloak:
    image: quay.io/keycloak/keycloak:7.0.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin_234
    ports:
      - '8280:8080'

#  db:
#    image: postgres:9.6-alpine
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_PASSWORD=postgres_234
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root_234
