version: '3'

services:
  server:
    build:
      context: .
    image: registry.balcia.com/balcia_dev/java/quarkus-ws
    ports:
      - '8080:8080'
      - '8778:8778'
      - '9779:9779'
    environment:
      - POSTGRES_PASSWORD=postgres_234
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - QUARKUS_PROFILE=dev

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin_234
    ports:
      - '8180:8080'

  db:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres_234
